# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.6.0.schema.json

PackageIdentifier: Grammarly.Grammarly_Pckgr
PackageVersion: 1.2.64.1318
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.6.0
